### ISSUE TITLE
Which include is used?

### ISSUE THREAD

**Issue by hbuitendijk** [HL7/v2-to-fhir#14]
Which include is the master for segment, message, datatype, vocabulary mapping?

https://github.com/HL7/v2-to-fhir/blob/master/input/includes/segment_mapping.md
or
https://github.com/HL7/v2-to-fhir/blob/master/tank/ig-data/input/includes/segment_mapping.md

**Comment by keithboone** [comment]
The second one gets copied by Sushi into the first location, so it's the source.  Confusing yes, but that's the way that the Tuna is sliced.

**Comment by hbuitendijk** [comment]
Okido.  I must have first put it into the wrong one.  Should stick on the next build then.
