### ISSUE TITLE
Please provide instructions

### ISSUE THREAD

**Issue by bluepuma77** [HL7/v2-to-fhir#32]
It would be great if you could provide some documentation.

How to setup, how to run, how to convert a v2 message to fhir.

**Comment by hbuitendijk** [comment]
Can you provide more background on what you meant?  This IG provides the guidance on what in HL7 v2 is mapped to what in FHIR R4.  Tools that actually map are outside the scope of this IG and would take this IG content as the knowledge input to then perform the conversion of an actual v2 message to an actual FHIR set of resources.

**Comment by bluepuma77** [comment]
My background is that I am a web developer and I want to make HL7v2 messages more easily digestible for me, like convert it to FHIR. I don't come from health care background, I know little Java from back in the days, don't know what an IG or Sushi store is. I searched Github for HL7v2 and found this repository which seems to include code.

"_This repository supports tools and content for the V2 to FHIR project._"

Two more sentences would be great to explain what it is, how the architecture looks like and what it does. Which one is the bigger project? Can it actually convert messages? From variable or file?

My assumption is there is a HL7v2-FHIR message converter included. Where to start, how can I run it to get something like `var fhir = parseHL7v2(msg_v2);`

Even better would be to provide a Docker file to have all dependencies automatically included.

My bigger picture: My final goal is to have a TCP-Server for HL7v2, transform the message to FHIR and then forward it via HTTP. If successful (status 200) send an ACK, else ERR back to the original sender.

**Comment by bluepuma77** [comment]
My background is that I am a web developer and I want to make HL7v2 messages more easily digestible for me, like convert it to FHIR. I searched Github for HL7v2 and found this repository which seems to include code. My assumption was there is a HL7v2-FHIR message converter included which I could use like `var fhir = parseHL7v2(msg_v2);`.

"This repository supports tools and content for the V2 to FHIR project."

Two more sentences would be great to explain what it is, how the architecture looks like and what it does. Which one is the bigger project?

**Comment by hbuitendijk** [comment]
The tools and content included are strictly to define the mappings, e.g., the original .csv files, the explanations/documentation, and the tools to convert the .csv files to .fsh/.json/.xml/.turtle into a ConceptMap expression.  In the future it may have tools to express them in FHIR Mapping language.  But that it is where it stops.  If you want to convert an actual v2 message to a FHIR construct, you will either need to create your own tools, or you use tools being build.  But those are all developed/maintained outside this environment.
