### ISSUE TITLE
Google spreadsheets or ones referenced here?

### ISSUE THREAD

**Issue by HMoen** [HL7/v2-to-fhir#38]
First, thanks for all the work being put  into this.

Which spreadsheet source is the most up to date and/or which one should be used?

Example: MSH segment. Options:

1. https://github.com/HL7/v2-to-fhir/blob/master/mappings/segments/HL7%20Segment%20-%20FHIR%20R4_%20MSH%5BMessageHeader%5D%20-%20R4.csv
2. https://docs.google.com/spreadsheets/d/13pgda5xl-PwCgB9j0axyymwwv7RJVcrIzY8Ah1y1Y1M/edit#gid=0

Thanks in advance.

**Comment by csnewman88** [comment]
The most recent mappings are in the Mapping worksheet at https://docs.google.com/spreadsheets/d/1PaFYPSSq4oplTvw_4OgOn6h2Bs_CMvCAU9CqC4tPBgk/edit#gid=0 which is available on the HL7 Confluence site at https://confluence.hl7.org/display/OO/2-To-FHIR+Project. Do keep in mind that the mappings are still a work in progress and subject to change.

**Comment by HMoen** [comment]
@csnewman88, appreciate the quick response!
