### ISSUE TITLE
Download only "Ready for Ballot"

### ISSUE THREAD

**Issue by keithboone** [HL7/v2-to-fhir#4]
Download only "Ready for Ballot"
Add support to convert.java to download only those sheets that are marked "Ready for Ballot"

**Comment by hbuitendijk** [comment]
I’ll be pinging you when I have all mapping spreadsheets properly marked for inclusion.

Hans J. Buitendijk, M.Sc., FHL7 | Director, Interoperability Strategy | hans.buitendijk@cerner.com<mailto:hans.buitendijk@cerner.com> | +1 610-219-2087 office/mobile | Cerner Corporation | www.cerner.com<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cerner.com%2F&data=02%7C01%7CHans.Buitendijk%40Cerner.com%7C46a83a5d4bb64fa0dc5d08d6980ea693%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C636863586028303617&sdata=OJQaj00RbusXrzTqEghLpDT1vCRhiA2bVi3oN59Km14%3D&reserved=0>

**Comment by keithboone** [comment]
Added -r_filename_ option that supports download of only "Ready for Ballot" items (looking in column 2 or 3 of the spreadsheets).
Verified that this works for messages list.
